export const LOGIN="LOGIN";
export const LOGOUT = "LOGOUT";
export const UPDATE_USER_LIST = "UPDATE_USER_LIST";
export const RECENT_MSSAGES = "RECENT_MSSAGES";
export const ADD_RECENT_MSSAGES = "ADD_RECENT_MSSAGES";
export const UPDATE_LOCATION = "UPDATE_LOCATION";
export const UPDATE_THREADS = "UPDATE_THREADS";
export const REFRESH_THREADS = "REFRESH_THREADS";
